import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { Store } from '../utils/Store'
import {ToastContainer} from 'react-toastify'
import { Menu } from '@headlessui/react'
import { signOut, useSession } from 'next-auth/react'
import DropdownLink from './DropdownLink'
import Cookies from 'js-cookie'

function Layout({title,children}) {
  const {status, data: session} = useSession()
  const {state, dispatch} = useContext(Store)
  const {cart}= state
  const [cartItemCount, setcartItemCount] = useState(0)
  useEffect(()=>{
    setcartItemCount(cart.cartItems.reduce((a,c) => a + c.quantity, 0))
  },[cart.cartItems])

  const logoutClickHandler = ()=>{
    Cookies.remove('cart')
    dispatch({type: 'CART_RESET'})
    signOut({callbackUrl: '/login'})
  }

  return (
    <>
     <Head>
        <title>{title ? title + ' - hoka' : 'hoka'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer limit={1}/>
    <div className="flex min-h-screen flex-col justify-between">
        <header className='text-lg'>
          <nav className='flex justify-between items-center h-12 shadow-md'>
            <Link href="/"> 
             <a className='text-lg font-bold'>Hoka</a>
            </Link>
            <div >
              <Link href="/cart">
                <a className='p-2'>Cart
                {cartItemCount > 0 && (
                  <span className='ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white'>{cartItemCount}</span>
                )}
                </a>
              </Link>

              
             {status === 'loading' ? ('Loding') : session?.user ?
              <Menu as='div' className = 'relative inline-block '>
              <Menu.Button className='text-blue-400'>
                {session.user.name}
              </Menu.Button>
              <Menu.Items className=' absolute right-0 w-56 bg-white origin-top-right shadow-lg'>
                <Menu.Item>
                  <DropdownLink className='dropdoen-link' href='/profile '>
                   Profile
                  </DropdownLink>
                </Menu.Item>

                <Menu.Item>
                  <DropdownLink className='dropdoen-link' href='/order-history '>
                   Order History
                  </DropdownLink>
                </Menu.Item>

                <Menu.Item>
                  <DropdownLink className='dropdoen-link' href='/profile '>
                   <a className='dropdown-link' href='#' onClick={logoutClickHandler}>
                    Logout
                   </a>
                  </DropdownLink>
                </Menu.Item>
              </Menu.Items>
             </Menu>
               
                :
              (
              <Link href="/login">
                <a>Login</a>
              </Link>
              )
            }
              
            </div>

          </nav>
        </header>

        <main className=' container m-auto mt-4 px-4'>{children}</main>

        <footer className=' flex justify-center items-center h-10 shadow-inner'>
          <p>copyright @ 2022 Hoka</p>
        </footer>
    </div>
    </>
  )
}

export default Layout