import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

function Layout({title,children}) {
  return (
    <>
     <Head>
        <title>{title ? title + ' - hoka' : 'hoka'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="flex min-h-screen flex-col justify-between">
        <header className='text-lg'>
          <nav className='flex justify-between items-center h-12 shadow-md'>
            <Link href="/"> 
             <a className='text-lg font-bold'>Hoka</a>
            </Link>
            <div >
              <Link href="/cart">
                <a className='p-2'>Cart</a>
              </Link>

              <Link href="/login">
                <a className='p-2'>Login</a>
              </Link>
            </div>

          </nav>
        </header>

        <main className=' container m-auto mt-4 px-4'>{children}</main>

        <footer className=' flex justify-center items-center h-10 shadow-inner'>
          <p>copyright @ 2022 Hoka</p>
        </footer>
    </div>
    </>
  )
}

export default Layout